### PR TITLE
Removes LuxCore

### PR DESCRIPTION
**Pull request by amznestebanpapp**
Relates to https://github.com/o3de/o3de/pull/6491

Signed-off-by: Esteban Papp <81431996+amznestebanpapp@users.noreply.github.com>

### CODE REVIEW

**Review by rgba16f — APPROVED** [review]

**Review by bosnichd — APPROVED** [review]

**Review by VickyAtAZ — CHANGES_REQUESTED** [review]
There are automated tests using this sample. 

In \o3de-atom-sampleviewer\Scripts\_FullTestSuite_.bv.lua
FastCheckSample('RPI/Shading'),
should be removed. 
and 
    RunScriptWrapper('scripts/PassTree.bv.luac'),
should be disabled. 

Other than that, can you create a jira to update PassTree.bv.lua text to use another sample instead of using RPI/shading sample.

**Comment by amznestebanpapp** [comment]
> scripts/PassTree.bv.luac

Issue created: https://github.com/o3de/o3de-atom-sampleviewer/issues/307
Sure, do you want me to also remove `PassTree.bv.luac`?
How was that test working if LuxCore was disabled? was it because of that `ShadingExampleComponent`? should I restore it and leave it without LuxCore's code?

**Comment by VickyAtAZ** [comment]
> 

The shading sample was created as the entrance to trigger luxcore via some ebus requests sent to luxcore. It still works if luxcore was disabled. It just won't launch luxcore viewport.
It can be removed since using luxcore was the main purpose for the sample. 

The PassTree.bv.luac test was an automated test to validate PassTree tool. It happened to use Shading sample as it test case. We still need the test but we need to update it to another sample (update the lua script and update the screenshots). 

I think it's okay to disable it from the full test suite so it won't block the ASV gpu AR and add a jira to track the work.

**Review by VickyAtAZ — APPROVED** [review]
I created a jira ATOM-16966 to track the update of PassTree.lv.lua

**Pull request merged**
