### PR TITLE
Merge stabilization/2210 to development

### PR DESCRIPTION
**Pull request by AMZN-daimini**
No conflicts

### CODE REVIEW

**Comment by rgba16f** [comment]
Looks like no code changes to merge?

**Comment by cgalvan** [comment]
> Looks like no code changes to merge?

Correct, because the original commit was later cherry-picked into the stabilization branch:

https://github.com/o3de/o3de-atom-sampleviewer/pull/505

**Review by cgalvan — APPROVED** [review]

**Review by galibzon — APPROVED** [review]

**Comment by AMZN-daimini** [comment]
Right, I didn't even notice... I can submit it just to update the history, or wait until the next sync merge?

**Review by gadams3 — APPROVED** [review]

**Comment by AMZN-daimini** [comment]
Decided to submit so history is preserved.

**Pull request merged**
